### ISSUE TITLE
Проблема с sudo

### ISSUE THREAD

**Issue by UnknownCrew44** [jorexdeveloper/termux-nethunter#10]
При том же sudo apt update && apt upgrade -y вылазит ошибка на счёт судо, я прописываю su просит пароль, пароль я не знаю, как установить свой пароль или поменять пользователя и войти уже в свою систему? Я использую калинетхантер на термуксе если что

**Comment by jorexdeveloper** [comment]
> При том же sudo apt update && apt upgrade -y вылазит ошибка на счёт судо, я прописываю su просит пароль, пароль я не знаю, как установить свой пароль или поменять пользователя и войти уже в свою систему? Я использую калинетхантер на термуксе если что

`chpasswd`
