### ISSUE TITLE
ASKING PASSWORD LOGIN

### ISSUE THREAD

**Issue by ANONSHOT** [jorexdeveloper/termux-nethunter#14]
When I started " nethunter root " it's asking password
What is the localhost and password 
![Uploading Screenshot_20241024_015209.jpg…]()

**Comment by jorexdeveloper** [comment]
Workaround for login issues.

```bash
$~ nh --command="/bin/bash -l"
```

That should be able to get you going, instead of the default `login` command.

Try `--help` for more information.
