### ISSUE TITLE
Please solve this issue, my device has good internet connection but still shows this error

### ISSUE THREAD

**Issue by sohampawar1866** [jorexdeveloper/termux-nethunter#9]
![IMG_20240918_182733.jpg](https://github.com/user-attachments/assets/e29a41d1-273f-4398-be71-5aca527fff2e)

**Comment by jorexdeveloper** [comment]
rootfs 

> ![IMG_20240918_182733.jpg](https://private-user-images.githubusercontent.com/178253448/368576702-e29a41d1-273f-4398-be71-5aca527fff2e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzg0MjksIm5iZiI6MTcyNzIzODEyOSwicGF0aCI6Ii8xNzgyNTM0NDgvMzY4NTc2NzAyLWUyOWE0MWQxLTI3M2YtNDM5OC1iZTcxLTVhY2E1MjdmZmYyZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwNDIyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2FjODc1MjAwMmU5YjU5ZGU0YjAzZjkzOGRhYzM0MTU5ODgwNzkzYTk2ZjE2ZWNhYjE5YjE3YjNhOWNhY2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ho2MNf3tUpuSiIQT2a5gc9DIrZ8rkhb6LAimCIPsWhk)

rootfs link needs update...

**Comment by jorexdeveloper** [comment]
Use this link..haven't got time to update script..any volunteers would do....

https://kali.download/nethunter-images/current/rootfs/

**Comment by jorexdeveloper** [comment]
added a quick solution (definetely untested!)...should resolve your problem...but i didnt change everything required..take care

https://github.com/jorexdeveloper/termux-nethunter/blob/main/install-nethunter-untested-update.sh

**Comment by jorexdeveloper** [comment]
Issue fixed!

**Comment by jorexdeveloper** [comment]
Issue fixed. Download links updated!
